import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  jsx: "transform",
  jsxFactory: "h",
  jsxFragment: "Fragment",
});

if (prod) {
	// Production build: build once and exit
	await context.rebuild();
	console.log("\n✓ Build complete!");
	console.log("📦 Release files:");
	console.log("   - main.js");
	if (existsSync("manifest.json")) {
		console.log("   - manifest.json");
	}
	if (existsSync("styles.css")) {
		console.log("   - styles.css");
	}
	console.log("\n💡 Upload these files to GitHub releases\n");
	await context.dispose();
	process.exit(0);
} else {
	// Development mode: watch for changes
	console.log("\n✓ Development build running in watch mode");
	console.log("📝 Building to main.js in root");
	console.log("💡 For production builds, run: npm run build\n");
	await context.watch();
}
